create or replace TABLE CUSTOMER (
	ID NUMBER(38,0) NOT NULL,
	CUSTOMER_FIRST_NAME VARCHAR(256),
	CUSTOMER_MIDDLE_NAME VARCHAR(256),
	CUSTOMER_LAST_NAME VARCHAR(256),
	CUSTOMER_ADDRESS VARCHAR(256),
	primary key (ID)
);