-- Temporary REGION
create table if not exists TMP.TMP_D_REGION_LU (
    ID NUMBER(38,0) NOT NULL,
    COUNTRY_ID NUMBER(38,0),
    REGION_DESC VARCHAR(256),
    PRIMARY KEY (ID),
    FOREIGN KEY (COUNTRY_ID) REFERENCES TMP.TMP_D_COUNTRY_LU(ID)
);

-- Temporary STORE
create table if not exists TMP.TMP_D_STORE_LU (
    ID NUMBER(38,0) NOT NULL,
    REGION_ID NUMBER(38,0),
    STORE_DESC VARCHAR(256),
    PRIMARY KEY (ID),
    FOREIGN KEY (REGION_ID) REFERENCES TMP.TMP_D_REGION_LU(ID)
);

-- Temporary CUSTOMER
create table if not exists TMP.TMP_D_CUSTOMER_LU (
    ID NUMBER(38,0) NOT NULL,
    CUSTOMER_FIRST_NAME VARCHAR(256),
    CUSTOMER_MIDDLE_NAME VARCHAR(256),
    CUSTOMER_LAST_NAME VARCHAR(256),
    CUSTOMER_ADDRESS VARCHAR(256),
    PRIMARY KEY (ID)
);

-- Temporary TRANSACTION
create table if not exists TMP.TMP_D_CATEGORY_LU (
    ID NUMBER(38,0) NOT NULL,
    CATEGORY_DESC VARCHAR(1024),
    PRIMARY KEY (ID)
);

-- Temporary TRANSACTION
create table if not exists TMP.TMP_D_SUBCATEGORY_LU (
    ID NUMBER(38,0) NOT NULL,
    CATEGORY_ID NUMBER(38,0),
    SUBCATEGORY_DESC VARCHAR(256),
    PRIMARY KEY (ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES TMP.TMP_D_CATEGORY_LU(ID)
);

-- Temporary PRODUCT
create table if not exists TMP.TMP_D_PRODUCT_LU (
    ID NUMBER(38,0) NOT NULL,
    SUBCATEGORY_ID NUMBER(38,0),
    PRODUCT_DESC VARCHAR(256),
    PRIMARY KEY (ID),
    FOREIGN KEY (SUBCATEGORY_ID) REFERENCES TMP.TMP_D_SUBCATEGORY_LU(ID)
);

-- Temporary SALES
create table if not exists TMP.TMP_F_SALES_TRXN_B (
    ID NUMBER,
    STORE_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    CUSTOMER_ID NUMBER,
    TRANSACTION_TIME TIMESTAMP,
    QUANTITY NUMBER,
    AMOUNT NUMBER(20,2),
    DISCOUNT NUMBER(20,2),
    PRIMARY KEY (ID),
    FOREIGN KEY (STORE_ID) REFERENCES TMP.TMP_D_STORE_LU(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES TMP.TMP_D_PRODUCT_LU(ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES TMP.TMP_D_CUSTOMER_LU(ID)
);

